# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d7656e3c7e2edbb7de8aa386f518a0b898f65b23b049f760455bb80e552dce24b1d9266ae3f2b1976f2a3fbfd6d30e7dd3ac963da7f2688c09a64b2523cdbd

test:
  secret_key_base: 85c0c129615c54143cf4b624dcb7a94b424e8cc9037ce62e9be8a39d2410cef4cfd4d7185ec63e43259f5e6fc11c3742503789c1ca30c36ebb85a2cd5719a2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
